FROM node:16-alpine

RUN apk add --no-cache \
  chromium

RUN apk add --update python3 make g++\
   && rm -rf /var/cache/apk/*

RUN mkdir /app && chown node:node /app
WORKDIR /app
USER node

COPY  --chown=node:node ./package*.json ./
COPY  --chown=node:node ./yarn.lock ./

RUN npm i ts-node typescript

RUN yarn install --ignore-optional

COPY --chown=node:node . .

CMD ["yarn", "dev"]
